
CREATE TABLE author (
                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                        "name" varchar(255) NULL,
                        CONSTRAINT author_pkey PRIMARY KEY (id)
);

CREATE TABLE book (
                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                      genre varchar(255) NULL,
                      publication_date date NULL,
                      quantity int4 NULL,
                      title varchar(255) NOT NULL,
                      author_id int8 NULL,
                      CONSTRAINT book_pkey PRIMARY KEY (id),
                      CONSTRAINT uk4sac2ubmnqva85r8bk8fxdvbf UNIQUE (author_id)
);


-- public.book foreign keys

ALTER TABLE public.book ADD CONSTRAINT fkklnrv3weler2ftkweewlky958 FOREIGN KEY (author_id) REFERENCES author(id);