spring.application.name=BookLibrary
#Open Api 3.0
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:phuoc123}

liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml

server.servlet.context-path=/book-lib
springdoc.swagger-ui.path=/swagger-ui.html


# Redis Server Configuration
#spring.data.redis.host=${REDIS_HOST:127.0.0.1}
#spring.data.redis.port=${REDIS_PORT:6379}
booklib.redis.url=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}

#Kafka config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=email-noti-group
booklib.kafka.topic=my_topic
booklib.kafka.email_list=email-list

# more config of kafka
spring.kafka.producer.retries=2
spring.kafka.producer.properties.delivery.timeout.ms=60000
spring.kafka.producer.properties.retry.backoff.ms=5000
spring.kafka.producer.properties.request.timeout.ms=30000
spring.kafka.producer.properties.linger.ms=100
spring.kafka.producer.properties.batch.size=16384